### ISSUE TITLE
Can't access Error class on PHP 7

### ISSUE THREAD

**Issue by feryardiant** [feryardiant/tokonlen#1]
Reported by Fandi on FB

```
Fatal error:
Uncaught Error: Access to undeclared static property: Error::$types in /app/system/helpers/common.php:164
```

This error only happen in deployment server,

**Comment by feryardiant** [comment]
```
PHP Warning:  set_error_handler() expects the argument (Error::errHandler) to be a valid callback in /system/includes/App.php on line 142
PHP Warning:  set_exception_handler() expects the argument (Error::excHandler) to be a valid callback in /system/includes/App.php on line 144
```

**Comment by feryardiant** [comment]
Wondering why all methods and properties from [`Error` class](https://github.com/feryardiant/tokonlen/blob/master/system/includes/Error.php) are inaccessible in PHP 7.0.0?

**Comment by ferdhika31** [comment]
masih 
Fatal error: Access to undeclared static property: Error::$types in C:\xampp\htdocs\tokonlen\system\includes\Error.php on line 55

saya pake PHP Versi 5.5.15

**Comment by feryardiant** [comment]
update script nya bang..

```
$ git pull origin master
```

:grin:
