### ISSUE TITLE
Validation extension image upload on admin page product

### ISSUE THREAD

**Issue by ferdhika31** [feryardiant/tokonlen#2]
Bug in  tokonlen/system/includes/Upload.php:34

```
       if (!copy($this->file['tmp_name'], $this->target.$filename)) {
            if (!move_uploaded_file($this->file['tmp_name'], $this->target.$this->file['name'])) {
                App::error('Upload gagal');
            }
        }
```

**Comment by feryardiant** [comment]
Hallo mas @ferdhika31.

Bisa lebih diperjelas lagi use case nya?

Thanks :grin:

**Comment by ferdhika31** [comment]
upload image produk di halaman admin nya bisa all extension.. bukan image doang :grin: 
nanti bisa ngapload backdoor kalo ga di validasi :grinning:

**Comment by feryardiant** [comment]
Oh, iya. emang gak tak kasih validasi :grin: 

Mau ngirim Pull Request? :wink:
